package model;
// Generated Mar 17, 2018 3:43:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name="movie"
    ,catalog="threadther"
)
public class Movie  implements java.io.Serializable {


     private Integer movieId;
     private String title;
     private String synopsis;
     private Double rating;
     private Integer duration;
     private String poster;
     private Integer status;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Movie() {
    }

    public Movie(String title, String synopsis, Double rating, Integer duration, String poster, Integer status, Set<Schedule> schedules) {
       this.title = title;
       this.synopsis = synopsis;
       this.rating = rating;
       this.duration = duration;
       this.poster = poster;
       this.status = status;
       this.schedules = schedules;
    }

    public Movie(String title, String synopsis, Double rating, Integer duration, String poster, Integer status) {
        this.title = title;
        this.synopsis = synopsis;
        this.rating = rating;
        this.duration = duration;
        this.poster = poster;
        this.status = status;
    }
    
    
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="movie_id", unique=true, nullable=false)
    public Integer getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    
    @Column(name="title", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="synopsis", length=1000)
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    
    @Column(name="rating", precision=22, scale=0)
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }

    
    @Column(name="duration")
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    
    @Column(name="poster", length=100)
    public String getPoster() {
        return this.poster;
    }
    
    public void setPoster(String poster) {
        this.poster = poster;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="movie")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }




}


