package model;
// Generated Mar 17, 2018 3:43:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScheduleId generated by hbm2java
 */
@Embeddable
public class ScheduleId  implements java.io.Serializable {


     private Date movieStart;
     private int studioNumber;

    public ScheduleId() {
    }

    public ScheduleId(Date movieStart, int studioNumber) {
       this.movieStart = movieStart;
       this.studioNumber = studioNumber;
    }
   


    @Column(name="movie_start", nullable=false, length=19)
    public Date getMovieStart() {
        return this.movieStart;
    }
    
    public void setMovieStart(Date movieStart) {
        this.movieStart = movieStart;
    }


    @Column(name="studio_number", nullable=false)
    public int getStudioNumber() {
        return this.studioNumber;
    }
    
    public void setStudioNumber(int studioNumber) {
        this.studioNumber = studioNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScheduleId) ) return false;
		 ScheduleId castOther = ( ScheduleId ) other; 
         
		 return ( (this.getMovieStart()==castOther.getMovieStart()) || ( this.getMovieStart()!=null && castOther.getMovieStart()!=null && this.getMovieStart().equals(castOther.getMovieStart()) ) )
 && (this.getStudioNumber()==castOther.getStudioNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMovieStart() == null ? 0 : this.getMovieStart().hashCode() );
         result = 37 * result + this.getStudioNumber();
         return result;
   }   


}


