package model;
// Generated Mar 17, 2018 3:43:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Studio generated by hbm2java
 */
@Entity
@Table(name="studio"
    ,catalog="threadther"
)
public class Studio  implements java.io.Serializable {


     private Integer studioNumber;
     private Cinema cinema;
     private String studioName;
     private Integer rowCapacity;
     private Integer colCapacity;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<Seat> seats = new HashSet<Seat>(0);

    public Studio() {
    }

    public Studio(Cinema cinema, String studioName, Integer rowCapacity, Integer colCapacity, Set<Schedule> schedules, Set<Seat> seats) {
       this.cinema = cinema;
       this.studioName = studioName;
       this.rowCapacity = rowCapacity;
       this.colCapacity = colCapacity;
       this.schedules = schedules;
       this.seats = seats;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="studio_number", unique=true, nullable=false)
    public Integer getStudioNumber() {
        return this.studioNumber;
    }
    
    public void setStudioNumber(Integer studioNumber) {
        this.studioNumber = studioNumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cinema_name")
    public Cinema getCinema() {
        return this.cinema;
    }
    
    public void setCinema(Cinema cinema) {
        this.cinema = cinema;
    }

    
    @Column(name="studio_name", length=20)
    public String getStudioName() {
        return this.studioName;
    }
    
    public void setStudioName(String studioName) {
        this.studioName = studioName;
    }

    
    @Column(name="row_capacity")
    public Integer getRowCapacity() {
        return this.rowCapacity;
    }
    
    public void setRowCapacity(Integer rowCapacity) {
        this.rowCapacity = rowCapacity;
    }

    
    @Column(name="col_capacity")
    public Integer getColCapacity() {
        return this.colCapacity;
    }
    
    public void setColCapacity(Integer colCapacity) {
        this.colCapacity = colCapacity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studio")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studio")
    public Set<Seat> getSeats() {
        return this.seats;
    }
    
    public void setSeats(Set<Seat> seats) {
        this.seats = seats;
    }




}


