package model;
// Generated Mar 17, 2018 3:43:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="threadther"
)
public class User  implements java.io.Serializable {


     private int userId;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private String profilePicture;
     private Customer customer;
     private Admin admin;
     private Cashier cashier;

    public User() {
    }

	
    public User(int userId) {
        this.userId = userId;
    }
    
    public User(int userId, String firstName, String lastName, String email, String password, String profilePicture, Customer customer, Admin admin, Cashier cashier) {
       this.userId = userId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.profilePicture = profilePicture;
       this.customer = customer;
       this.admin = admin;
       this.cashier = cashier;
    }

    public User(String firstName, String lastName, String email, String password, String profilePicture) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.profilePicture = profilePicture;
    }
    
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="first_name", length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="profile_picture", length=100)
    public String getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Cashier getCashier() {
        return this.cashier;
    }
    
    public void setCashier(Cashier cashier) {
        this.cashier = cashier;
    }




}


